# Generated by Django 4.1.5 on 2023-01-21 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
